apiVersion: apps/v1
kind: Deployment
metadata:
  name: large-scale-analysis-app
  namespace: {{NAMESPACE}}
spec:
  selector:
    matchLabels:
      app: large-scale-analysis-app
  replicas: 1
  template:
    metadata:
      labels:
        app: large-scale-analysis-app
    spec:
      containers:
        - name: large-scale-analysis-container
          image: {{IMAGE_NAME}}
          ports:
            - name: app-port
              containerPort: 8080
              protocol: TCP
          env:
            - name: KUMULUZEE_VERSION
              value: {{VERSION}}
            - name: KUMULUZEE_ENV_NAME
              value: {{ENV_NAME}}
            - name: KUMULUZEE_ENV_PROD
              value: "{{ENV_PROD}}"
            - name: KUMULUZEE_SERVER_BASEURL
              value: https://large-scale-analysis{{ENV_SUFFIX}}.mydna.codes
            - name: KUMULUZEE_SERVER_HTTP_PORT
              value: "8080"
            - name: KUMULUZEE_GRPC_CLIENTS1_ADDRESS
              value: analysis-result-service.{{NAMESPACE}}
            - name: KUMULUZEE_GRPC_CLIENTS1_PORT
              value: "8081"
            - name: KUMULUZEE_GRPC_CLIENTS0_ADDRESS
              value: sequence-bank-service.{{NAMESPACE}}
            - name: KUMULUZEE_GRPC_CLIENTS0_PORT
              value: "8081"
            - name: KUMULUZEE_STREAMING_KAFKA_CONSUMER_BOOTSTRAP-SERVERS
              value: kafka.kafka:9092
            - name: KUMULUZEE_HEALTH_CHECKS_KAFKAHEALTHCHECK_BOOTSTRAPSERVERS
              value: kafka.kafka:9092
          livenessProbe:
            httpGet:
              path: /health/live
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: app-port
            initialDelaySeconds: 30
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: large-scale-analysis-service
  namespace: {{NAMESPACE}}
  labels:
    app: large-scale-analysis-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: app-port
      name: rest
  selector:
    app: large-scale-analysis-app